Beaver Builder: Resolve `Uncaught TypeError: sowbForms.getWidgetIdBase`
This resolves an error caused by the WB Widget Admin JS not being loaded due to the colour picker JS being prevented from being loaded. Unfortunately, it does mean that our color field will act as a standard text field.

`fl-builder.min.js?ver=2.7.0.5:1 "Uncaught TypeError: sowbForms.getWidgetIdBase is not a function" on line 1 of /wp-content/plugins/so-widgets-bundle/compat/beaver-builder/sowb-beaver-builder.min.js?ver=6.2.2.`